cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAgeStrict: true

tasks:
  lint:
    dependsOn:
      - lint:eslint
      - lint:svelte

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - ts-api-utils@2.3.0
