blockExoticSubdeps: true

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440 # 1 Day

minimumReleaseAgeExclude:
  - svelte-check@4.4.3

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - ts-api-utils@2.3.0
