autoDedupe: true

catalogPrune: true

engineStrict: true

minimumReleaseAgeStrict: true

saveTypes: true

tasks:
  ci:
    dependsOn:
      - fmt
      - lint
  fmt:
    dependsOn:
      - build
  lint:
    dependsOn:
      - lint:eslint
      - lint:svelte
  lint:eslint:
    dependsOn:
      - build
  lint:svelte:
    dependsOn:
      - build

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - ts-api-utils@2.3.0
